<?php
	
/*
|--------------------------------------------------------------------------
| Sample Skills List
|--------------------------------------------------------------------------
|
| List of sample skills used by database seeders and factories
|
*/

return [
	'Analytics',
	'Analytical',
	'Applications',
	'Application Development',
	'Attention to Detail',
	'Architecture',
	'Big Data',
	'Business Analytics',
	'Business Intelligence',
	'Business Process Modeling',
	'Cloud Computing',
	'Code',
	'Coding',
	'Computer',
	'Communication',
	'Content Strategy',
	'Content Management',
	'Configuration',
	'Critical Thinking',
	'Customer Support',
	'Database',
	'Data Analysis',
	'Data Analytics',
	'Data Intelligence',
	'Data Mining',
	'Data Science',
	'Data Strategy',
	'Data Storage',
	'Database Administration',
	'Design',
	'Desktop Support',
	'Developer',
	'Development',
	'Documentation',
	'Emerging Technologies',
	'File Systems',
	'Fireworks',
	'Flexibility',
	'Hardware',
	'Help Desk',
	'Illustrator',
	'Implementation',
	'Internet',
	'Information Systems',
	'Installation',
	'Integrated Technologies',
	'IT Manager',
	'IT Optimization',
	'IT Security',
	'IT Soft Skills',
	'IT Solutions',
	'IT Support',
	'Java',
	'Javascript',
	'Languages',
	'Logical Thinking',
	'Leadership',
	'Linux',
	'Lisp',
	'Management',
	'Messaging',
	'Methodology',
	'Metrics',
	'Microsoft Office',
	'Mobile Applications',
	'Motivation',
	'Networks',
	'Network Operations',
	'Networking',
	'Operating Systems',
	'Operations',
	'Organization',
	'Photoshop',
	'Php',
	'Presentation',
	'Programming',
	'Problem Solving',
	'Product Development',
	'Product Support',
	'Product Management',
	'Product Training',
	'Project Management',
	'Python',
	'Repairs',
	'Reporting',
	'Ruby',
	'Search Engine Optimization (SEO)',
	'Security',
	'Self Motivated',
	'Self Starting',
	'Servers',
	'Software',
	'Software Development',
	'Software Engineering',
	'Software Quality Assurance (QA)',
	'Storage',
	'Support',
	'Systems Software',
	'Team Building',
	'Team Oriented',
	'Teamwork',
	'Tech Skills Listed by Job',
	'Tech Support',
	'Technical',
	'Technology',
	'Technical Services',
	'Tech Skills Listed by Job',
	'Technical Support',
	'Technical Writing',
	'Testing',
	'Tools',
	'Time Management',
	'Technical Writing',
	'Training',
	'Troubleshooting',
	'UI / UX',
	'User Experience Design',
	'Virtualization',
	'Web',
	'Web Development',
	'Web Design',
	'Work Independently',
];